[2023-07-25 22:05:03,330] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T22:00:00+00:00 [queued]>
[2023-07-25 22:05:03,339] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T22:00:00+00:00 [queued]>
[2023-07-25 22:05:03,340] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:05:03,341] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 22:05:03,341] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 22:05:03,356] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2023-07-25 22:00:00+00:00
[2023-07-25 22:05:03,362] {standard_task_runner.py:52} INFO - Started process 13737 to run task
[2023-07-25 22:05:03,365] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'calc-rates', 'insert_data', 'scheduled__2023-07-25T22:00:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/calc_rates.py', '--cfg-path', '/tmp/tmpwfatp8r6', '--error-file', '/tmp/tmptt18tvd3']
[2023-07-25 22:05:03,366] {standard_task_runner.py:80} INFO - Job 286: Subtask insert_data
[2023-07-25 22:05:03,435] {task_command.py:371} INFO - Running <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T22:00:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 22:05:03,506] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=calc-rates
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T22:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T22:00:00+00:00
[2023-07-25 22:05:03,521] {logging_mixin.py:115} INFO - rate_date:  2023-07-25
[2023-07-25 22:05:03,523] {logging_mixin.py:115} INFO - value_:  29117.92105299999820
[2023-07-25 22:05:03,533] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-07-25 22:05:03,555] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/calc_rates.py", line 93, in insert_data
    cursor.execute(f"INSERT INTO {dag_variables.get('table_name')} (ingest_datetime, rate_date, rate_base, rate_target, value_ ) valueS('{ingest_datetime}','{results['rate_date']}', '{dag_variables.get('rate_base')}', '{dag_variables.get('rate_target')}', '{results['value_']}');")
psycopg2.errors.UndefinedTable: relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^

[2023-07-25 22:05:03,568] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=calc-rates, task_id=insert_data, execution_date=20230725T220000, start_date=20230725T220503, end_date=20230725T220503
[2023-07-25 22:05:03,581] {standard_task_runner.py:97} ERROR - Failed to execute job 286 for task insert_data (relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^
; 13737)
[2023-07-25 22:05:03,618] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 22:05:03,673] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
