[2023-07-26 01:00:03,822] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-26T00:55:00+00:00 [queued]>
[2023-07-26 01:00:03,837] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-26T00:55:00+00:00 [queued]>
[2023-07-26 01:00:03,838] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:00:03,839] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 01:00:03,840] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 01:00:03,855] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2023-07-26 00:55:00+00:00
[2023-07-26 01:00:03,861] {standard_task_runner.py:52} INFO - Started process 4150 to run task
[2023-07-26 01:00:03,867] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'calc-rates', 'insert_data', 'scheduled__2023-07-26T00:55:00+00:00', '--job-id', '406', '--raw', '--subdir', 'DAGS_FOLDER/calc_rates.py', '--cfg-path', '/tmp/tmpfy6dc4nk', '--error-file', '/tmp/tmp0xsuq5g5']
[2023-07-26 01:00:03,876] {standard_task_runner.py:80} INFO - Job 406: Subtask insert_data
[2023-07-26 01:00:03,948] {task_command.py:371} INFO - Running <TaskInstance: calc-rates.insert_data scheduled__2023-07-26T00:55:00+00:00 [running]> on host 661c8d62a693
[2023-07-26 01:00:04,005] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=calc-rates
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-26T00:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-26T00:55:00+00:00
[2023-07-26 01:00:04,015] {logging_mixin.py:115} INFO - rate_date:  2023-07-26
[2023-07-26 01:00:04,016] {logging_mixin.py:115} INFO - value_:  29105.18421099999977
[2023-07-26 01:00:04,025] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-07-26 01:00:04,041] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/calc_rates.py", line 93, in insert_data
    cursor.execute(f"INSERT INTO {dag_variables.get('table_name')} (ingest_datetime, rate_date, rate_base, rate_target, value_ ) valueS('{ingest_datetime}','{results['rate_date']}', '{dag_variables.get('rate_base')}', '{dag_variables.get('rate_target')}', '{results['value_']}');")
psycopg2.errors.UndefinedTable: relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^

[2023-07-26 01:00:04,050] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=calc-rates, task_id=insert_data, execution_date=20230726T005500, start_date=20230726T010003, end_date=20230726T010004
[2023-07-26 01:00:04,061] {standard_task_runner.py:97} ERROR - Failed to execute job 406 for task insert_data (relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^
; 4150)
[2023-07-26 01:00:04,077] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 01:00:04,110] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
