[2023-07-25 20:38:23,217] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [queued]>
[2023-07-25 20:38:23,234] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [queued]>
[2023-07-25 20:38:23,235] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:23,236] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:23,237] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:23,263] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 12:00:00+00:00
[2023-07-25 20:38:23,270] {standard_task_runner.py:52} INFO - Started process 9194 to run task
[2023-07-25 20:38:23,274] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T12:00:00+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpukjgs8lz', '--error-file', '/tmp/tmpee1sdvs2']
[2023-07-25 20:38:23,276] {standard_task_runner.py:80} INFO - Job 170: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:23,428] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:23,580] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T12:00:00+00:00
[2023-07-25 20:38:25,275] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:25,293] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T120000, start_date=20230725T203823, end_date=20230725T203825
[2023-07-25 20:38:25,337] {standard_task_runner.py:97} ERROR - Failed to execute job 170 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9194)
[2023-07-25 20:38:25,483] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:25,626] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:05:17,523] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [queued]>
[2023-07-26 05:05:17,593] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [queued]>
[2023-07-26 05:05:17,601] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:17,602] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:05:17,614] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:17,686] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 12:00:00+00:00
[2023-07-26 05:05:17,698] {standard_task_runner.py:52} INFO - Started process 1086 to run task
[2023-07-26 05:05:17,762] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T12:00:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp1bmkwe4o', '--error-file', '/tmp/tmpfbbin_5k']
[2023-07-26 05:05:17,775] {standard_task_runner.py:80} INFO - Job 258: Subtask fetch_exchange_rates_task
[2023-07-26 05:05:18,111] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T12:00:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:05:18,412] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T12:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T12:00:00+00:00
[2023-07-26 05:05:18,873] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:05:18,874] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:05:18,894] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:05:19,255] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:05:19,256] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:05:19,264] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:05:19,286] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "99,603666"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,603666"

[2023-07-26 05:05:19,312] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T120000, start_date=20230726T050517, end_date=20230726T050519
[2023-07-26 05:05:19,446] {standard_task_runner.py:97} ERROR - Failed to execute job 258 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "99,603666"
CONTEXT:  COPY exchange_rates_eur, line 2, column exchange_rate: "99,603666"
; 1086)
[2023-07-26 05:05:19,515] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:05:19,731] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
