[2023-07-25 20:38:15,873] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [queued]>
[2023-07-25 20:38:15,909] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [queued]>
[2023-07-25 20:38:15,915] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:15,916] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:15,917] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:15,940] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 11:10:00+00:00
[2023-07-25 20:38:15,953] {standard_task_runner.py:52} INFO - Started process 9168 to run task
[2023-07-25 20:38:15,959] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T11:10:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp71sujlkt', '--error-file', '/tmp/tmp6_avkm0w']
[2023-07-25 20:38:15,965] {standard_task_runner.py:80} INFO - Job 166: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:16,144] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:16,316] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T11:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T11:10:00+00:00
[2023-07-25 20:38:18,527] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:18,538] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T111000, start_date=20230725T203815, end_date=20230725T203818
[2023-07-25 20:38:18,549] {standard_task_runner.py:97} ERROR - Failed to execute job 166 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9168)
[2023-07-25 20:38:18,571] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:18,599] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:05:02,095] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [queued]>
[2023-07-26 05:05:02,138] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [queued]>
[2023-07-26 05:05:02,146] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:02,166] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:05:02,168] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:05:02,233] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 11:10:00+00:00
[2023-07-26 05:05:02,249] {standard_task_runner.py:52} INFO - Started process 964 to run task
[2023-07-26 05:05:02,266] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T11:10:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpwi7ygj58', '--error-file', '/tmp/tmpv0omtzkd']
[2023-07-26 05:05:02,268] {standard_task_runner.py:80} INFO - Job 227: Subtask fetch_exchange_rates_task
[2023-07-26 05:05:02,545] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T11:10:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:05:02,756] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T11:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T11:10:00+00:00
[2023-07-26 05:05:03,183] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:05:03,185] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:05:03,196] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:05:03,211] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2622163,5"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2622163,5"

[2023-07-26 05:05:03,239] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T111000, start_date=20230726T050502, end_date=20230726T050503
[2023-07-26 05:05:03,273] {standard_task_runner.py:97} ERROR - Failed to execute job 227 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2622163,5"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2622163,5"
; 964)
[2023-07-26 05:05:03,332] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:05:03,554] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
