[2023-07-25 23:40:03,799] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T23:35:00+00:00 [queued]>
[2023-07-25 23:40:03,809] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T23:35:00+00:00 [queued]>
[2023-07-25 23:40:03,810] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 23:40:03,811] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 23:40:03,811] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 23:40:03,829] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2023-07-25 23:35:00+00:00
[2023-07-25 23:40:03,837] {standard_task_runner.py:52} INFO - Started process 175 to run task
[2023-07-25 23:40:03,840] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'calc-rates', 'insert_data', 'scheduled__2023-07-25T23:35:00+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/calc_rates.py', '--cfg-path', '/tmp/tmp4np5k_da', '--error-file', '/tmp/tmp5sy_1_9f']
[2023-07-25 23:40:03,841] {standard_task_runner.py:80} INFO - Job 355: Subtask insert_data
[2023-07-25 23:40:03,918] {task_command.py:371} INFO - Running <TaskInstance: calc-rates.insert_data scheduled__2023-07-25T23:35:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 23:40:03,994] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=calc-rates
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T23:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T23:35:00+00:00
[2023-07-25 23:40:04,009] {logging_mixin.py:115} INFO - rate_date:  2023-07-25
[2023-07-25 23:40:04,010] {logging_mixin.py:115} INFO - value_:  29090.21052599999893
[2023-07-25 23:40:04,021] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-07-25 23:40:04,044] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/calc_rates.py", line 93, in insert_data
    cursor.execute(f"INSERT INTO {dag_variables.get('table_name')} (ingest_datetime, rate_date, rate_base, rate_target, value_ ) valueS('{ingest_datetime}','{results['rate_date']}', '{dag_variables.get('rate_base')}', '{dag_variables.get('rate_target')}', '{results['value_']}');")
psycopg2.errors.UndefinedTable: relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^

[2023-07-25 23:40:04,057] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=calc-rates, task_id=insert_data, execution_date=20230725T233500, start_date=20230725T234003, end_date=20230725T234004
[2023-07-25 23:40:04,066] {standard_task_runner.py:97} ERROR - Failed to execute job 355 for task insert_data (relation "rates" does not exist
LINE 1: INSERT INTO rates (ingest_datetime, rate_date, rate_base, ra...
                    ^
; 175)
[2023-07-25 23:40:04,092] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 23:40:04,128] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
