[2023-07-25 20:34:41,231] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [queued]>
[2023-07-25 20:34:41,357] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [queued]>
[2023-07-25 20:34:41,393] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:41,397] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:34:41,398] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:41,553] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:30:00+00:00
[2023-07-25 20:34:41,599] {standard_task_runner.py:52} INFO - Started process 8816 to run task
[2023-07-25 20:34:41,601] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:30:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp6a41iapn', '--error-file', '/tmp/tmpt3hw40ka']
[2023-07-25 20:34:41,603] {standard_task_runner.py:80} INFO - Job 96: Subtask fetch_exchange_rates_task
[2023-07-25 20:34:42,005] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:34:42,306] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:30:00+00:00
[2023-07-25 20:34:44,220] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:34:44,235] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T003000, start_date=20230725T203441, end_date=20230725T203444
[2023-07-25 20:34:44,255] {standard_task_runner.py:97} ERROR - Failed to execute job 96 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 8816)
[2023-07-25 20:34:44,315] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:34:44,368] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:03:19,920] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [queued]>
[2023-07-26 05:03:19,994] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [queued]>
[2023-07-26 05:03:19,995] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:19,996] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:03:19,998] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:20,152] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 00:30:00+00:00
[2023-07-26 05:03:20,186] {standard_task_runner.py:52} INFO - Started process 257 to run task
[2023-07-26 05:03:20,249] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T00:30:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp_e8kdyhx', '--error-file', '/tmp/tmprzlo6mkk']
[2023-07-26 05:03:20,253] {standard_task_runner.py:80} INFO - Job 22: Subtask fetch_exchange_rates_task
[2023-07-26 05:03:20,894] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T00:30:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:03:21,309] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T00:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T00:30:00+00:00
[2023-07-26 05:03:22,101] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:03:22,102] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:03:22,138] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:03:22,194] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 99, in fetch_exchange_rates
    cur.execute(copy_query)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "2622163,5"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2622163,5"

[2023-07-26 05:03:22,252] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T003000, start_date=20230726T050319, end_date=20230726T050322
[2023-07-26 05:03:22,337] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task fetch_exchange_rates_task (invalid input syntax for type numeric: "2622163,5"
CONTEXT:  COPY exchange_rates_btc, line 2, column exchange_rate: "2622163,5"
; 257)
[2023-07-26 05:03:22,468] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:03:22,550] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
