[2023-07-25 20:38:02,377] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [queued]>
[2023-07-25 20:38:02,417] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [queued]>
[2023-07-25 20:38:02,419] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:02,422] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:38:02,424] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:38:02,451] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 07:20:00+00:00
[2023-07-25 20:38:02,459] {standard_task_runner.py:52} INFO - Started process 9092 to run task
[2023-07-25 20:38:02,487] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T07:20:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpj5de44jd', '--error-file', '/tmp/tmpkkqhgvtp']
[2023-07-25 20:38:02,497] {standard_task_runner.py:80} INFO - Job 142: Subtask fetch_exchange_rates_task
[2023-07-25 20:38:02,686] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:38:02,826] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T07:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T07:20:00+00:00
[2023-07-25 20:38:04,547] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:38:04,592] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T072000, start_date=20230725T203802, end_date=20230725T203804
[2023-07-25 20:38:04,661] {standard_task_runner.py:97} ERROR - Failed to execute job 142 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 9092)
[2023-07-25 20:38:04,741] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:38:05,056] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:04:28,942] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [queued]>
[2023-07-26 05:04:28,956] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [queued]>
[2023-07-26 05:04:28,957] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:04:28,958] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:04:28,959] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:04:28,975] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 07:20:00+00:00
[2023-07-26 05:04:28,982] {standard_task_runner.py:52} INFO - Started process 721 to run task
[2023-07-26 05:04:28,986] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T07:20:00+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmp5zb050bt', '--error-file', '/tmp/tmp_lmcc_yt']
[2023-07-26 05:04:28,991] {standard_task_runner.py:80} INFO - Job 160: Subtask fetch_exchange_rates_task
[2023-07-26 05:04:29,124] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T07:20:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:04:29,239] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T07:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T07:20:00+00:00
[2023-07-26 05:04:29,601] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 73, in fetch_exchange_rates
    df = pd.read_csv(f'./csv_files/exchange_latest_{base}.csv', decimal=',', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-07-26 05:04:29,658] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T072000, start_date=20230726T050428, end_date=20230726T050429
[2023-07-26 05:04:29,702] {standard_task_runner.py:97} ERROR - Failed to execute job 160 for task fetch_exchange_rates_task (No columns to parse from file; 721)
[2023-07-26 05:04:29,775] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:04:29,929] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
