[2023-07-25 20:34:41,572] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [queued]>
[2023-07-25 20:34:41,684] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [queued]>
[2023-07-25 20:34:41,688] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:41,697] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-25 20:34:41,701] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-25 20:34:41,804] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 02:10:00+00:00
[2023-07-25 20:34:41,821] {standard_task_runner.py:52} INFO - Started process 8818 to run task
[2023-07-25 20:34:41,829] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T02:10:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpycjxozca', '--error-file', '/tmp/tmp8sm_vdav']
[2023-07-25 20:34:41,835] {standard_task_runner.py:80} INFO - Job 97: Subtask fetch_exchange_rates_task
[2023-07-25 20:34:42,071] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [running]> on host 661c8d62a693
[2023-07-25 20:34:42,337] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T02:10:00+00:00
[2023-07-25 20:34:44,158] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 69, in fetch_exchange_rates
    load_to_postgres = PostgresOperator(
NameError: name 'PostgresOperator' is not defined
[2023-07-25 20:34:44,173] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T021000, start_date=20230725T203441, end_date=20230725T203444
[2023-07-25 20:34:44,185] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task fetch_exchange_rates_task (name 'PostgresOperator' is not defined; 8818)
[2023-07-25 20:34:44,214] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-25 20:34:44,248] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-26 05:03:23,396] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [queued]>
[2023-07-26 05:03:23,419] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [queued]>
[2023-07-26 05:03:23,420] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:23,421] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-26 05:03:23,421] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-26 05:03:23,478] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fetch_exchange_rates_task> on 2023-07-25 02:10:00+00:00
[2023-07-26 05:03:23,530] {standard_task_runner.py:52} INFO - Started process 269 to run task
[2023-07-26 05:03:23,628] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fetch_exchange_rates_dag', 'fetch_exchange_rates_task', 'scheduled__2023-07-25T02:10:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/my_calc_rates.py', '--cfg-path', '/tmp/tmpv75jszqi', '--error-file', '/tmp/tmpbk246w9_']
[2023-07-26 05:03:23,644] {standard_task_runner.py:80} INFO - Job 33: Subtask fetch_exchange_rates_task
[2023-07-26 05:03:24,252] {task_command.py:371} INFO - Running <TaskInstance: fetch_exchange_rates_dag.fetch_exchange_rates_task scheduled__2023-07-25T02:10:00+00:00 [running]> on host acb6bca32630
[2023-07-26 05:03:24,583] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marina_z
AIRFLOW_CTX_DAG_ID=fetch_exchange_rates_dag
AIRFLOW_CTX_TASK_ID=fetch_exchange_rates_task
AIRFLOW_CTX_EXECUTION_DATE=2023-07-25T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-25T02:10:00+00:00
[2023-07-26 05:03:25,475] {logging_mixin.py:115} INFO - Save a new file exchange_latest_BTC.csv
[2023-07-26 05:03:25,476] {logging_mixin.py:115} INFO - Create a new table exchange_latest_BTC
[2023-07-26 05:03:25,486] {logging_mixin.py:115} INFO - Insert into table exchange_latest_BTC
[2023-07-26 05:03:25,856] {logging_mixin.py:115} INFO - Save a new file exchange_latest_EUR.csv
[2023-07-26 05:03:25,859] {logging_mixin.py:115} INFO - Create a new table exchange_latest_EUR
[2023-07-26 05:03:25,864] {logging_mixin.py:115} INFO - Insert into table exchange_latest_EUR
[2023-07-26 05:03:26,352] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_calc_rates.py", line 73, in fetch_exchange_rates
    df = pd.read_csv(f'./csv_files/exchange_latest_{base}.csv', decimal=',', index_col=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2023-07-26 05:03:26,408] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fetch_exchange_rates_dag, task_id=fetch_exchange_rates_task, execution_date=20230725T021000, start_date=20230726T050323, end_date=20230726T050326
[2023-07-26 05:03:26,462] {standard_task_runner.py:97} ERROR - Failed to execute job 33 for task fetch_exchange_rates_task (No columns to parse from file; 269)
[2023-07-26 05:03:26,504] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-26 05:03:26,632] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
